openapi: 3.0.0
info:
  contact:
    email: info@brockmann-consult.de
  description: Restful API for handling xcube Services
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: xcube Generator API
  version: 2.0.0
servers:
- url: https://xcube-gen.brockmann-consult.de/api/v2
- url: https://stage.xcube-gen.brockmann-consult.de/api/v2
tags:
- name: users
- name: cubegens
- name: callbacks
- name: oauth
paths:
  /:
    get:
      description: Get service info
      operationId: get_service_info
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiServiceInformationResponse'
          description: service information
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: api error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: service not found
      summary: get service info
      x-openapi-router-controller: xcube_hub.controllers.default
  /users:
    put:
      description: |
        Create a user
      operationId: put_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User configuration
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUserResponse'
          description: User created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
        - oAuthorization:
          - create:users
      summary: Create a user
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/{user_id}:
    get:
      description: |
        Get info of a user
      operationId: get_user_by_user_id
      parameters:
        - description: User ID
          explode: false
          in: path
          name: user_id
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
             application/json:
               schema:
                 $ref: '#/components/schemas/ApiUserResponse'
          description: User created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      tags:
        - users
      security:
         - oAuthorization:
           - read:users
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/{user_id}/apps:
    get:
      description: |
        Get user's apps
      operationId: get_user_apps
      parameters:
        - description: User ID
          explode: false
          in: path
          name: user_id
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: User added
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      tags:
        - users
      security:
        - oAuthorization:
            - read:users
            - read:roles
            - read:role_members
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/{user_id}/apps/{app_id}:
    put:
      description: Add user to app
      operationId: put_user_to_app
      parameters:
        - description: User ID
          explode: false
          in: path
          name: user_id
          required: true
          schema:
            type: string
          style: simple
        - description: App ID
          explode: false
          in: path
          name: app_id
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: User added
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      tags:
        - users
      security:
        - oAuthorization:
            - update:users
            - read:roles
            - create:role_members
      x-openapi-router-controller: xcube_hub.controllers.users
    delete:
      description: |
        Remove a user from app
      operationId: delete_user_from_app
      parameters:
        - description: User ID
          explode: false
          in: path
          name: user_id
          required: true
          schema:
            type: string
          style: simple
        - description: App ID
          explode: false
          in: path
          name: app_id
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: User deleted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      tags:
        - users
      security:
        - oAuthorization:
            - update:users
            - delete:role_members
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/credentials:
    get:
      description: |
        Get info of a user
      operationId: get_user_credentials
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCredentialsResponse'
          description: Credentials returned
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
      security:
        - oAuthorization:
            - read:users
      x-openapi-router-controller: xcube_hub.controllers.users
  /cubegens:
    delete:
      description: |
        Delete all cubegens
      operationId: delete_cubegens
      responses:
        "200":
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Delete all cubegens
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List user cubegens
      operationId: get_cubegens
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCubegensResponse'
          description: List cubegens
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: List cubegens
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    put:
      description: |
        Create a jcubegen
      operationId: create_cubegen
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CubegenConfig'
        description: Cubegen configuration
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCubegenResponse'
          description: Create a cubegen
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Create a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/info:
    post:
      description: |
        Receive cost information of using a service
      operationId: get_cubegen_info
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CostConfig'
        description: Cost configuration
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCubegenInfoResponse'
          description: costs for using the service
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: api error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: no cost information found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Receive cost information for runnning a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}:
    delete:
      description: |
        Delete a cubegen
      operationId: delete_cubegen
      parameters:
      - description: Cubegen ID
        explode: false
        in: path
        name: cubegen_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCubegenResponse'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Delete a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List specific cubegen
      operationId: get_cubegen
      parameters:
      - description: Cubegen ID
        explode: false
        in: path
        name: cubegen_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCubegenResponse'
          description: User cubegen information
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: List specific cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}/callbacks:
    put:
      description: Add a callbacks for a cubegen
      operationId: put_callback_by_cubegen_id
      parameters:
      - description: Cubegen ID
        explode: false
        in: path
        name: cubegen_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Callback'
        description: Callbacks
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCallbackResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: User not found
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Add a callback for a cubegen
      tags:
      - callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks
  /oauth/token:
    post:
      description: Get authorization token
      operationId: oauth_token_post
      requestBody:
        content:
          application/json:
#          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OauthToken'
        description: OauthToken
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiOauthResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Client ID not found
      summary: Get authorization token
      tags:
      - oauth
      x-openapi-router-controller: xcube_hub.controllers.oauth
  /stores:
    get:
      description: Get stores
      operationId: get_stores
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiStoresResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Api Error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: No stores found
      summary: Get stores
      tags:
        - stores
      x-openapi-router-controller: xcube_hub.controllers.stores
components:
  schemas:
    ApiResponse:
      type: object
    ApiErrorResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          required:
            - traceback
          properties:
            traceback:
              type: string
    ApiUserResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            result:
              $ref: '#/components/schemas/User'
    ApiCredentialsResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            result:
              $ref: '#/components/schemas/UserMetaData'
    ApiCubegenResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - $ref: '#/components/schemas/CubegenStatus'
    ApiCubegenInfoResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - $ref: '#/components/schemas/CubegenInfo'
    ApiCubegensResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            result:
              type: array
              items:
                $ref: '#/components/schemas/CubegenStatus'
    ApiServiceInformationResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            result:
              $ref: '#/components/schemas/ServiceInformation'
    ApiCallbackResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            result:
              $ref: '#/components/schemas/Callback'
    ApiStoresResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          required:
            - result
          properties:
            result:
              $ref: '#/components/schemas/Stores'
    ApiOauthResponse:
      example:
        access_token: access_token
        token_type: token_type
      properties:
        access_token:
          type: string
        token_type:
          type: string
      required:
      - access_token
      - token_type
      type: object
    ServiceInformation:
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: string
        serverStartTime:
          format: date-time
          type: string
        serverCurrentTime:
          format: date-time
          type: string
        serverPID:
          type: integer
        chartVersion:
          type: string
        mockServices:
          type: string
        runLocal:
          type: boolean
      type: object
    Stores:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        store_id:
          type: string
    CostConfig:
      allOf:
      - $ref: '#/components/schemas/CubegenConfig'
    CubegenInfo:
      type: object
      properties:
        dataset_descriptor:
          $ref: '#/components/schemas/DatasetDescriptor'
        size_estimation:
          $ref: '#/components/schemas/SizeEstimation'
        cost_estimation:
          $ref: '#/components/schemas/CostEstimation'
    CubegenConfig:
      example:
        output_config:
          store_id: store_id
          store_params: '{}'
        cube_config:
          spatial_res: 6.027456183070403
          crs: crs
          time_range:
          - 2000-01-23
          - 2000-01-23
          bbox:
          - 1.4658129805029452
          - 1.4658129805029452
          variable_names:
          - variable_names
          - variable_names
          time_period: time_period
        input_configs:
        - store_id: store_id
          data_id: data_id
          open_params:
            tile_size:
            - 0.8008281904610115
            - 0.8008281904610115
        - store_id: store_id
          data_id: data_id
          open_params:
            tile_size:
            - 0.8008281904610115
            - 0.8008281904610115
      properties:
        input_configs:
          items:
            $ref: '#/components/schemas/CubegenConfigInputConfig'
          type: array
        input_config:
          $ref: '#/components/schemas/CubegenConfigInputConfig'
        cube_config:
          $ref: '#/components/schemas/CubegenConfigCubeConfig'
        output_config:
          $ref: '#/components/schemas/CubegenConfigOutputConfig'
      required:
        - cube_config
        - output_config
      type: object
    Callback:
      required:
        - state
        - sender
      type: object
      properties:
        state:
          type: object
          properties:
            label:
              type: string
            total_work:
              type: number
            error:
              oneOf:
                - type: string
                - type: boolean
            progress:
              type: number
            elapsed:
              type: number
        sender:
          type: string
    CubegenStatus:
      type: object
      required:
        - cubegen_id
        - status
      properties:
        cubegen_id:
          type: string
        progress:
          $ref: '#/components/schemas/Callback'
        status:
          type: object
          required:
            - active
            - completion_time
            - failed
            - start_time
            - succeeded
          properties:
            logs:
              items:
                type: string
              type: array
            active:
              oneOf:
                - type: integer
                - type: boolean
              nullable: true
            start_time:
              format: date-time
              type: string
            failed:
              oneOf:
                - type: integer
                - type: boolean
              nullable: true
            succeeded:
              oneOf:
                - type: integer
                - type: boolean
              nullable: true
            completion_time:
              format: date-time
              type: string
    OauthToken:
      example:
        audience: audience
        grant_type: grant_type
        client_secret: client_secret
        client_id: client_id
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        audience:
          type: string
        grant_type:
          type: string
      required:
      - audience
      - client_id
      - client_secret
      type: object
    CubegenConfigOpenParams:
      example:
        tile_size:
        - 0.8008281904610115
        - 0.8008281904610115
      properties:
        tile_size:
          items:
            type: number
          type: array
      type: object
    CubegenConfigInputConfig:
      example:
        store_id: store_id
        data_id: data_id
        open_params:
          tile_size:
            - 0.8008281904610115
            - 0.8008281904610115
      properties:
        store_id:
          type: string
        data_id:
          type: string
        open_params:
          $ref: '#/components/schemas/CubegenConfigOpenParams'
      required:
        - data_id
        - store_id
      type: object
    CubegenConfigCubeConfig:
      properties:
        variable_names:
          items:
            type: string
          type: array
        crs:
          type: string
        spatial_res:
          type: number
        bbox:
          items:
            maxItems: 4
            minItems: 4
            type: number
          type: array
        time_range:
          items:
            format: date
            maxItems: 2
            minItems: 1
            type: string
          type: array
        time_period:
          type: string
      required:
      - bbox
      - crs
      - spatial_res
      - time_period
      - time_range
      - variable_names
      type: object
    CubegenConfigOutputConfig:
      properties:
        store_id:
          type: string
        store_params:
          type: object
      required:
      - store_id
      type: object
    CostEstimation:
      type: object
      properties:
        required:
          type: integer
          default: 1
        available:
          type: integer
          default: 1
        limit:
          type: integer
          default: 1
    SizeEstimation:
      type: object
      properties:
        image_size:
          type: array
          items:
            type: integer
        tile_size:
          type: array
          items:
            type: integer
        num_tiles:
          type: array
          items:
            type: integer
        num_variables:
          type: integer
        num_requests:
          type: integer
        num_bytes:
          type: integer
    DatasetDescriptor:
      type: object
      properties:
        type_specifier:
          type: string
        data_id:
          type: string
        crs:
          type: string
        bbox:
          type: array
          items:
            type: number
            format: int32
            default: [0, 0, 0, 0]
        time_range:
          type: array
          items:
            type: string
            format: date
          default: ["2020-01-01", "2020-01-15"]
        time_period:
          type: string
          default: "1D"
        data_vars:
          type: object
        spatial_res:
          type: number
          format: float
          default: 0.01
        dims:
          type: object
          properties:
            time:
              type: integer
              default: 1
            lat:
              type: number
              format: float
            lon:
              type: number
              format: float
            x:
              type: number
              format: float
            y:
              type: number
              format: float
    DataStore:
      type: object
      required:
        - title
        - store_id
        - cost_params
        - store_params
      properties:
        title:
          type: string
        store_id:
          type: string
        cost_params:
          type: object
          required:
            - input_pixels_per_unit
            - output_pixels_per_punit
          properties:
            input_pixels_per_unit:
              type: integer
              minimum: 1
            input_punits_weight:
              type: number
              default: 1.0
              minimum: 0.0
              exclusiveMinimum: true
            output_pixels_per_punit:
              type: integer
              minimum: 1
            output_punits_weight:
              type: number
              default: 1.0
              minimum: 0.0
              exclusiveMinimum: true
        store_params:
          type: object
          properties:
            api_url:
              type: string
              format: url
      - store_params
      type: object
    UserMetaData:
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
          format: password
      additionalProperties: true
    AppMetaData:
      type: object
      properties:
        geodb_role:
          type: string
      additionalProperties: true
    Identity:
      type: object
      properties:
        connection:
          type: string
        user_id:
          type: string
        provider:
          type: string
        isSocial:
          type: boolean
    User:
      type: object
      required:
        - email
        - username
        - given_name
        - family_name
        - user_metadata
      properties:
        user_id:
          type: string
        email:
          type: string
          format: email
        email_verified:
          type: boolean
        username:
          type: string
        created_at:
          type: string
          format: 'date-time'
        updated_at:
          type: string
          format: 'date-time'
        connection:
          type: string
        identities:
          type: array
          items:
            $ref: '#/components/schemas/Identity'
        app_metadata:
          $ref: '#/components/schemas/AppMetaData'
        user_metadata:
          $ref: '#/components/schemas/UserMetaData'
        picture:
          type: string
        name:
          type: string
        nickname:
          type: string
        multifactor:
          type: array
          items:
            type: object
        last_ip:
          type: string
        last_login:
          type: string
        logins_count:
          type: integer
        blocked:
          type: boolean
        given_name:
          type: string
        family_name:
          type: string
  securitySchemes:
    oAuthorization:
      description: This API uses Oauth 2 with the implicit grant flow.
      flows:
        clientCredentials:
          scopes:
            manage_cubegens: Read cubegen status and result
          tokenUrl: http://localhost:8080/api/v2/oauth/token
      type: oauth2
      x-tokenInfoFunc: xcube_hub.controllers.authorization.check_oauthorization
      x-scopeValidateFunc: xcube_hub.controllers.authorization.validate_scope_oauthorization
